language: csharp
solution: ProjectARM.sln
install:
  - nuget restore ProjectARM.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ProjectARM.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./ManipulationSystemLibraryTests/bin/Release/ManipulationSystemLibraryTests.dll